/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KeyFinder;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Scott's PC
 */
public class KeyFinderGUI extends javax.swing.JFrame {
   String a;

    /**
     * Creates new form KeyGUI
     */
    public KeyFinderGUI() {
        initComponents();
        outputTextArea.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFrameFobs = new javax.swing.JFrame();
        fobsJComboBox = new javax.swing.JComboBox<>();
        inputTextField = new javax.swing.JTextField();
        attributeLabel = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        fobsLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        jFrameKeys = new javax.swing.JFrame();
        searchBtn1 = new javax.swing.JButton();
        keysLabel = new javax.swing.JLabel();
        Attribute = new javax.swing.JComboBox<>();
        KeySearch = new javax.swing.JTextField();
        attributeLabel1 = new javax.swing.JLabel();
        jFrameLostKeys = new javax.swing.JFrame();
        lostKeysComboBox = new javax.swing.JComboBox<>();
        inputTextField1 = new javax.swing.JTextField();
        searchBtn2 = new javax.swing.JButton();
        lostKeysLabel = new javax.swing.JLabel();
        attributeLabel2 = new javax.swing.JLabel();
        jFrameAddDialog = new javax.swing.JFrame();
        keyBtn = new javax.swing.JRadioButton();
        fobBtn = new javax.swing.JRadioButton();
        lostKeyBtn = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFrameEditDialog = new javax.swing.JFrame();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        rguLogoJLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        lostKeysBtn = new javax.swing.JButton();
        searchFobsBtn = new javax.swing.JButton();
        searchKeysBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        loginMenuItem = new javax.swing.JMenuItem();

        jFrameFobs.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrameFobs.setBounds(new java.awt.Rectangle(200, 200, 400, 300));

        fobsJComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fobsJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff/Fob Name", "Fob Number" }));

        inputTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        attributeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attributeLabel.setForeground(new java.awt.Color(153, 0, 230));
        attributeLabel.setText("Select Attribute");

        searchBtn.setText("Search");

        fobsLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        fobsLabel.setForeground(new java.awt.Color(153, 0, 230));
        fobsLabel.setText("Fobs");

        textLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textLabel.setForeground(new java.awt.Color(153, 0, 230));
        textLabel.setText("Enter Text:");

        javax.swing.GroupLayout jFrameFobsLayout = new javax.swing.GroupLayout(jFrameFobs.getContentPane());
        jFrameFobs.getContentPane().setLayout(jFrameFobsLayout);
        jFrameFobsLayout.setHorizontalGroup(
            jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameFobsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameFobsLayout.createSequentialGroup()
                        .addComponent(fobsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameFobsLayout.createSequentialGroup()
                        .addGroup(jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fobsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attributeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameFobsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jFrameFobsLayout.setVerticalGroup(
            jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameFobsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fobsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attributeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameFobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fobsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jFrameKeys.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrameKeys.setBounds(new java.awt.Rectangle(200, 200, 400, 300));

        searchBtn1.setText("Search");

        keysLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        keysLabel.setForeground(new java.awt.Color(68, 198, 111));
        keysLabel.setText("Keys:");

        Attribute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Key #", "Key Type", "Allocated To", "Location", " " }));
        Attribute.setToolTipText("");
        Attribute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttributeActionPerformed(evt);
            }
        });

        KeySearch.setText("Enter Text");

        attributeLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attributeLabel1.setForeground(new java.awt.Color(68, 198, 111));
        attributeLabel1.setText("Select Attribute");

        javax.swing.GroupLayout jFrameKeysLayout = new javax.swing.GroupLayout(jFrameKeys.getContentPane());
        jFrameKeys.getContentPane().setLayout(jFrameKeysLayout);
        jFrameKeysLayout.setHorizontalGroup(
            jFrameKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameKeysLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jFrameKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameKeysLayout.createSequentialGroup()
                        .addComponent(keysLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameKeysLayout.createSequentialGroup()
                        .addComponent(KeySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jFrameKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Attribute, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attributeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameKeysLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jFrameKeysLayout.setVerticalGroup(
            jFrameKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameKeysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keysLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Attribute, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(searchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jFrameLostKeys.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrameLostKeys.setBounds(new java.awt.Rectangle(200, 200, 400, 300));

        lostKeysComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputTextField1.setText("Enter Text");

        searchBtn2.setText("Search");

        lostKeysLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lostKeysLabel.setForeground(new java.awt.Color(68, 157, 191));
        lostKeysLabel.setText("Lost Keys:");

        attributeLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        attributeLabel2.setForeground(new java.awt.Color(68, 157, 191));
        attributeLabel2.setText("Select Attribute");

        javax.swing.GroupLayout jFrameLostKeysLayout = new javax.swing.GroupLayout(jFrameLostKeys.getContentPane());
        jFrameLostKeys.getContentPane().setLayout(jFrameLostKeysLayout);
        jFrameLostKeysLayout.setHorizontalGroup(
            jFrameLostKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameLostKeysLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jFrameLostKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameLostKeysLayout.createSequentialGroup()
                        .addComponent(lostKeysLabel)
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameLostKeysLayout.createSequentialGroup()
                        .addComponent(inputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFrameLostKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lostKeysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attributeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
            .addGroup(jFrameLostKeysLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(searchBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrameLostKeysLayout.setVerticalGroup(
            jFrameLostKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameLostKeysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lostKeysLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrameLostKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lostKeysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(searchBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jFrameAddDialog.setBounds(new java.awt.Rectangle(100, 100, 400, 480));

        keyBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keyBtn.setText("Key");
        keyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyBtnActionPerformed(evt);
            }
        });

        fobBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fobBtn.setText("Fob");
        fobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fobBtnActionPerformed(evt);
            }
        });

        lostKeyBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lostKeyBtn.setText("Lost Key");
        lostKeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostKeyBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Select the Type");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Select the Type");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Select the Type");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Select the Type");

        javax.swing.GroupLayout jFrameAddDialogLayout = new javax.swing.GroupLayout(jFrameAddDialog.getContentPane());
        jFrameAddDialog.getContentPane().setLayout(jFrameAddDialogLayout);
        jFrameAddDialogLayout.setHorizontalGroup(
            jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameAddDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyBtn)
                    .addComponent(fobBtn)
                    .addComponent(lostKeyBtn))
                .addGap(37, 37, 37)
                .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                        .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        jFrameAddDialogLayout.setVerticalGroup(
            jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameAddDialogLayout.createSequentialGroup()
                .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(keyBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fobBtn))
                    .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(13, 13, 13)
                .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameAddDialogLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jFrameAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lostKeyBtn)
                            .addComponent(jLabel9)))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        buttonGroup2.add(keyBtn);
        buttonGroup2.add(fobBtn);
        buttonGroup2.add(lostKeyBtn);

        jFrameEditDialog.setBounds(new java.awt.Rectangle(100, 100, 350, 490));

        jButton2.setText("Delete");

        jButton3.setText("Done");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Edit:");

        javax.swing.GroupLayout jFrameEditDialogLayout = new javax.swing.GroupLayout(jFrameEditDialog.getContentPane());
        jFrameEditDialog.getContentPane().setLayout(jFrameEditDialogLayout);
        jFrameEditDialogLayout.setHorizontalGroup(
            jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEditDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameEditDialogLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrameEditDialogLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField8)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jFrameEditDialogLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jFrameEditDialogLayout.setVerticalGroup(
            jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameEditDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrameEditDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(1980, 1080));

        addBtn.setBackground(new java.awt.Color(77, 0, 77));
        addBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        rguLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New_RGU_logo.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/questionMark_pic.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/key_pic.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fob_pic.png"))); // NOI18N

        editBtn.setBackground(new java.awt.Color(77, 0, 77));
        editBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        lostKeysBtn.setBackground(new java.awt.Color(148, 50, 129));
        lostKeysBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lostKeysBtn.setForeground(new java.awt.Color(255, 255, 255));
        lostKeysBtn.setText("Lost Keys");
        lostKeysBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostKeysBtnActionPerformed(evt);
            }
        });

        searchFobsBtn.setBackground(new java.awt.Color(148, 50, 129));
        searchFobsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchFobsBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchFobsBtn.setText("Search Fobs");
        searchFobsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFobsBtnActionPerformed(evt);
            }
        });

        searchKeysBtn.setBackground(new java.awt.Color(148, 50, 129));
        searchKeysBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchKeysBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchKeysBtn.setText("Search Keys");
        searchKeysBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKeysBtnActionPerformed(evt);
            }
        });

        outputTextArea.setEditable(false);
        outputTextArea.setBackground(new java.awt.Color(204, 204, 204));
        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(searchFobsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(searchKeysBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lostKeysBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(146, 146, 146)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(rguLogoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1820, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(searchKeysBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(searchFobsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lostKeysBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(174, 174, 174))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(rguLogoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(915, Short.MAX_VALUE)))
        );

        fileJMenu.setText("File");

        loadMenuItem.setText("Load");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(loadMenuItem);

        saveMenuItem.setText("Save");
        fileJMenu.add(saveMenuItem);
        fileJMenu.add(jSeparator1);

        loginMenuItem.setText("Login/Logout");
        fileJMenu.add(loginMenuItem);

        jMenuBar2.add(fileJMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
  
             // if (this.jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                //String str = "File Loaded:\n";
               // }
               KeyFinder ld = new KeyFinder();
              ld.loadData(); 
              
               
             //  }
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void AttributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttributeActionPerformed

    }//GEN-LAST:event_AttributeActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        jFrameAddDialog.show();
        jFrameAddDialog.setDefaultCloseOperation(jFrameAddDialog.HIDE_ON_CLOSE);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        jFrameEditDialog.show();
        outputTextArea.setEditable(true);
        jFrameEditDialog.setDefaultCloseOperation(jFrameEditDialog.HIDE_ON_CLOSE);

    }//GEN-LAST:event_editBtnActionPerformed

    private void lostKeysBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostKeysBtnActionPerformed
        jFrameLostKeys.show();
        jFrameLostKeys.setDefaultCloseOperation(jFrameLostKeys.HIDE_ON_CLOSE);

        //LostKeysDialog lkd = new LostKeysDialog();
        //lkd.setVisible(true);
        //lkd.setDefaultCloseOperation(lkd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_lostKeysBtnActionPerformed

    private void searchFobsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFobsBtnActionPerformed
        jFrameFobs.show();
        jFrameFobs.setDefaultCloseOperation(jFrameFobs.HIDE_ON_CLOSE);

        //FobsDialog fd = new FobsDialog();
        //fd.setVisible(true);
        //fd.setDefaultCloseOperation(fd.HIDE_ON_CLOSE);
    }//GEN-LAST:event_searchFobsBtnActionPerformed

    private void searchKeysBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKeysBtnActionPerformed
        jFrameKeys.show();
        //final KeysDialog kd = new KeysDialog();
        //kd.setVisible(true);
        jFrameKeys.setDefaultCloseOperation(jFrameKeys.HIDE_ON_CLOSE);

        /* try {
            //Get the excel file.
            FileInputStream file = new FileInputStream(new File("src\\main\\resources\\Key Records Sample.xlsx").getAbsolutePath());

            //Get workbook for XLS file.
            XSSFWorkbook yourworkbook = new XSSFWorkbook(file);

            //Get first sheet from the workbook.
            //If there have >1 sheet in your workbook, you can change it here IF you want to edit other sheets.
            final XSSFSheet sheet1 = yourworkbook.getSheetAt(1);

            kd.Attribute.addItemListener(new ItemListener(){
                @Override
                public void itemStateChanged(ItemEvent ie) {
                    Object item = kd.Attribute.getSelectedItem();
                    if ("Key #".equals(item)){
                        outputTextArea.append("20");
                        Row row = sheet1.getRow(0);
                    } else if ("Key Type".equals(item)){
                        outputTextArea.append("40");
                    } else if ("Allocated To".equals(item)){
                        outputTextArea.append("45");
                    } else if ("Location".equals(item)){
                        outputTextArea.append("60");

                    }
                }
            }); */

            //if(ie.getStateChange()== ItemEvent.SELECTED){
                //a = kd.Attribute.getSelectedItem().toString();
                //outputTextArea.append(a);

                //  }

            //  }

        //   });

    }//GEN-LAST:event_searchKeysBtnActionPerformed

    private void keyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyBtnActionPerformed
        // Make all Labels and boxes to Visible
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        
        jTextField1.setVisible(true);
        jTextField4.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        
        
       //Set all Labels tot the correct
        jLabel6.setText("Key #");
        jLabel7.setText("Key Type");
        jLabel8.setText("Allocated to");
        jLabel9.setText("Location");
                
    }//GEN-LAST:event_keyBtnActionPerformed

    private void fobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fobBtnActionPerformed
        //make the appropriate lables visable
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        
        //set the text for the labels and then make unused labels invisible
        jLabel6.setText("Staff/Fob Name");
        jLabel7.setText("Fob Number");
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        
        
    }//GEN-LAST:event_fobBtnActionPerformed

    private void lostKeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostKeyBtnActionPerformed

        //make the labels visible and unused labels invisible
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(false);
        
        
        jTextField3.setVisible(true);
        jTextField4.setVisible(false);
        
        //set text for the labels
        jLabel6.setText("Key #");
        jLabel7.setText("Quantity");
        jLabel8.setText("Type");
        
        
        
    }//GEN-LAST:event_lostKeyBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<String> addingItem =new ArrayList<String>();
        
        
        
        
         if( keyBtn.isSelected()){
             
             addingItem.add(jTextField1.getText());        
             addingItem.add(jTextField4.getText());    
             addingItem.add(jTextField2.getText());    
             addingItem.add(jTextField3.getText());
             
            //add to key spreadsheet
            
        }
        else if(fobBtn.isSelected()){            
                  
            addingItem.add(jTextField1.getText());        
            addingItem.add(jTextField4.getText());     
            
            //add to fob spreadsheet
        }
        
        else if(lostKeyBtn.isSelected()){
            
            addingItem.add(jTextField1.getText());        
            addingItem.add(jTextField4.getText());               
            addingItem.add(jTextField2.getText()); 
             
             
             //add to lost keys spreadsheet
        }
        
        else{
           JOptionPane.showMessageDialog(null, "Please select the Type:", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyFinderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyFinderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyFinderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyFinderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KeyGUI().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KeyGUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Attribute;
    public static javax.swing.JTextField KeySearch;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel attributeLabel;
    private javax.swing.JLabel attributeLabel1;
    private javax.swing.JLabel attributeLabel2;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton editBtn;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JRadioButton fobBtn;
    private javax.swing.JComboBox<String> fobsJComboBox;
    private javax.swing.JLabel fobsLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JTextField inputTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrameAddDialog;
    private javax.swing.JFrame jFrameEditDialog;
    private javax.swing.JFrame jFrameFobs;
    private javax.swing.JFrame jFrameKeys;
    private javax.swing.JFrame jFrameLostKeys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JRadioButton keyBtn;
    private javax.swing.JLabel keysLabel;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JRadioButton lostKeyBtn;
    private javax.swing.JButton lostKeysBtn;
    private javax.swing.JComboBox<String> lostKeysComboBox;
    private javax.swing.JLabel lostKeysLabel;
    public static javax.swing.JTextArea outputTextArea;
    private javax.swing.JLabel rguLogoJLabel;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchBtn1;
    private javax.swing.JButton searchBtn2;
    private javax.swing.JButton searchFobsBtn;
    private javax.swing.JButton searchKeysBtn;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
